themes and plugins are now copied over into app directory on container start
linuxserver/docker-rutorrent pull request #101
Opened 2018-12-31 15:46 UTC by alex-phillips

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

2018-12-31 16:15 UTC, aptalca requested changes

2018-12-31 16:15 UTC, aptalca commented on root/etc/cont-init.d/50-config
>  [[ ! -e /config/themes ]] && \
I think this should be `[[ -e /config/themes ]]`, is that right?

2018-12-31 16:55 UTC, alex-phillips commented on root/etc/cont-init.d/50-config
>  [[ ! -e /config/themes ]] && \
And that's  why we review :-P

2018-12-31 17:13 UTC, aptalca approved these changes

2018-12-31 17:13 UTC, merged

2020-02-05 19:05 UTC, lordvalium commented
How does that work @alex-phillips ? I have no folder /config/plugins. 
I would like to add filemanager. But dont know how.

2020-02-07 14:48 UTC, Anon0511 commented
> How does that work @alex-phillips ? I have no folder /config/plugins.
> I would like to add filemanager. But dont know how.

Hey, you have to create that folder manually in the root of your persistent directory. From there it is the standard like having another folder per plugin. Make sure of the user permissions in there.

Although I think Filemanager did not work when I tested it afterwards since it needs a deeper integration I think. Maybe I missed something. Let me know.

2020-02-17 01:28 UTC, dannymichel commented
so you're saying if my ``-v /data/rutorrent:/config`` i should make a folder called ``/data/rutorrent/plugins`` and that plugin should load? why isn't this in the documentation?

2020-02-17 06:03 UTC, Anon0511 commented
Yeah that is correct. 
I dont know either why it is hidden everywhere.

2020-02-17 06:28 UTC, dannymichel commented
> Yeah that is correct.
> I dont know either why it is hidden everywhere.

do you think they have some issue with users using their own plugins?

2020-02-17 06:47 UTC, Anon0511 commented
No I dont think so. But the Feature to provide your own plugins has been patched in to after I made a request for that. So maybe it just got forgotten or so.

2020-02-17 06:48 UTC, Anon0511 commented
And dont have the idea to install autodl-irssi, that wont work that easy. I already use a customized fork of this Container with irssi.

2020-02-17 08:26 UTC, j0nnymoe commented
You can add in additional software into our containers by doing this: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
This saves the need to fork.